safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"
      author: "John Casey"

siteTitle: "The Shop @LCfE"
siteUrl: "http://freemakers.github.io/"
projectTitle: ""
tagline: "Collaboration Spaces and Help for LCfE Members"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org

markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
